import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { domain, teamSize, duration, technology } = await req.json();

    const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY");
    if (!GEMINI_API_KEY) {
      throw new Error("GEMINI_API_KEY is not configured in Supabase Secrets");
    }

    const systemInstruction = `You are a premier Software Engineering and Project Management (SEPM) academic advisor.
Your mission is to generate innovative, academic-grade capstone/course project ideas for engineering students.
Every project MUST explicitly solve a clear real-world problem and possess a distinct uniqueness factor compared to standard generic GitHub repositories.`;

    const userPrompt = `Generate 5 innovative, realistic software engineering project title recommendations with these criteria:
- Target Domain: ${domain}
- Team Size: ${teamSize} students
- Project Timeline: ${duration} weeks
- Technology Stack: ${technology}

For each of the 5 projects, return a JSON object with:
1. "title": A professional, concise, academic-grade project title.
2. "description": 2-3 sentences explaining what the system does and its key functional modules.
3. "problemSolved": Exactly what specific real-world gap, user pain point, or operational inefficiency this project solves.
4. "uniquenessFactor": What makes this project distinct, novel, or superior compared to existing standard open-source boilerplate projects.
5. "complexity": "Low", "Medium", or "High".

Return ONLY a valid JSON array of objects with keys: ["title", "description", "problemSolved", "uniquenessFactor", "complexity"].
Do not wrap in markdown quotes if possible, or return strictly valid JSON.`;

    const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}`;

    const response = await fetch(geminiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        contents: [
          {
            role: "user",
            parts: [{ text: `${systemInstruction}\n\n${userPrompt}` }],
          },
        ],
        generationConfig: {
          temperature: 0.7,
          topP: 0.95,
          responseMimeType: "application/json",
        },
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("Gemini API error:", response.status, errorText);
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: "Gemini API rate limit reached. Please retry in a few moments." }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      return new Response(
        JSON.stringify({ error: `Gemini API error: ${response.status}` }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const geminiData = await response.json();
    const candidateText = geminiData.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!candidateText) {
      throw new Error("No response generated by Gemini AI");
    }

    let projects = [];
    try {
      // Parse JSON directly
      projects = JSON.parse(candidateText.trim());
    } catch (parseError) {
      console.warn("Direct JSON parse failed, cleaning text:", parseError);
      const cleanJson = candidateText
        .replace(/```json/g, "")
        .replace(/```/g, "")
        .trim();
      projects = JSON.parse(cleanJson);
    }

    return new Response(
      JSON.stringify({ projects }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("generate-titles error:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Internal error generating titles" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
